# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "imaalemS" do |server|
    server.vm.box = "debian/trixie64"
    server.vm.hostname = "imaalemS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "imaalemS"
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "imaalemSW" do |worker|
    worker.vm.box = "debian/trixie64"
    worker.vm.hostname = "imaalemSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "imaalemSW"
      vb.cpus = 1
      vb.memory = 1024
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end

end
